### PR TITLE
Add configuration for css custom properties

### PR DESCRIPTION
**Pull request by Exotelis**
Make it possible to optimize custom properties as well :)

- [x] Test 
- [x] Code styling valid
- [x] Squashed commits

Have a great day

### CODE REVIEW

**Comment by Exotelis** [comment]
Of course, other value optimizers would also make sense here. Maybe we can list all of them and I'll update my pr. Furthermore, it would also be possible to parse the custom properties name to determine which optimizer should be applied. E.g. `--prefix-color-primary` would use the color value optimizers etc.

**Comment by jakubpawlowicz** [comment]
Hey @Exotelis - thanks for suggesting this. I think colors and units are the two most frequent use cases for CSS variables, so maybe we should include units into the default list?

Another thing - please include a switch in level 1 optimizations allowing people to disable it (it can stay enabled by default).

**Comment by jakubpawlowicz** [comment]
@Exotelis please check #1217 - kudos for your idea, but I had to make it more configurable thus I decided to implement it differently.

**Comment by Exotelis** [comment]
Hey @jakubpawlowicz 

My apologies I didn't update my pr in time - I had no spare time to continue working on this. 
Thank you for taking care of this and adding the modifications, much appreciated.

**Comment by jakubpawlowicz** [comment]
No problem, glad it's solved now. Take care, and again thanks for your help!

**Pull request closed without merging**
